###
POST  https://flask-feme.herokuapp.com/api/v1/auth HTTP/1.1
content-type: application/json

{
    "username": "test1@gmail.com",
    "password": "testing123"
}

###
GET  http://flask-feme.herokuapp.com/api/v1/users
Authorization : JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTcwNzE5NDksImlhdCI6MTYxNDQ3OTk0OSwibmJmIjoxNjE0NDc5OTQ5LCJpZGVudGl0eSI6MX0.YGBHPFXz3XjMojn1-6YVSdTUCPN-zrUdtymSW2-SYJk

###
GET  http://flask-feme.herokuapp.com/api/v1/roles
Authorization : JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTcwMjkwNTcsImlhdCI6MTYxNDQzNzA1NywibmJmIjoxNjE0NDM3MDU3LCJpZGVudGl0eSI6MX0.AP5hMrH9H36uC0eqbu1wzNeVSm56ysRB_dhUQ5MfbMc

###
GET  https://flask-feme.herokuapp.com/dev-api/v1/trades

###
GET  https://flask-feme.herokuapp.com/dev-api/v1/settings