"""empty message

Revision ID: 850ee69563f7
Revises: b60ffc419245
Create Date: 2021-02-27 09:51:42.863926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850ee69563f7'
down_revision = 'b60ffc419245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('example', 'sex')
    # ### end Alembic commands ###
